# Generated by Django 5.1.2 on 2024-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(upload_to='social_icons/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
