# Generated by Django 5.1.2 on 2024-10-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
