# Generated by Django 5.1.2 on 2024-10-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='title',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
