# Generated by Django 4.2.14 on 2024-10-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_researchinterests_description_alter_about_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='year',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
