# Generated by Django 5.1.2 on 2024-10-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_category_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
