# Generated by Django 5.1.2 on 2024-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_remove_certification_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='about/files/'),
        ),
    ]
