# Generated by Django 5.1.2 on 2024-10-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_about_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='file',
        ),
        migrations.AddField(
            model_name='about',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
