# Generated by Django 5.1.2 on 2024-10-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_about_file_about_download_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='about/files/'),
        ),
    ]
