# Generated by Django 5.1.2 on 2024-10-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_skillscategory_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillscategory',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
