# Generated by Django 5.1.2 on 2024-10-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.DeleteModel(
            name='SkillsCategory',
        ),
    ]
