# Generated by Django 5.1.2 on 2024-10-22 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
                ('grade', models.CharField(max_length=300, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='year',
        ),
        migrations.AddField(
            model_name='education',
            name='cGPALastLwo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='cGPASpecialized',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='cPGA',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='advisors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisors', to='portfolio.advisors'),
        ),
        migrations.AddField(
            model_name='education',
            name='thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='portfolio.thesis'),
        ),
    ]
