# Generated by Django 5.1.2 on 2024-10-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_advisors_thesis_remove_education_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
