# Generated by Django 5.1.2 on 2024-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notebook_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/notebooks/'),
        ),
    ]
