# Generated by Django 5.1.2 on 2024-10-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_project_notebook_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notebook_file',
        ),
    ]
