# Generated by Django 5.1.2 on 2024-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_remove_project_notebook_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
